# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: synrep
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=3.5.0=py38h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - babel=2.11.0=py38h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py38h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.7.22=hbcca054_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py38h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.1.2=py38h06a4308_0
  - cryptography=39.0.1=py38h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fontconfig=2.14.1=h52c9d5c_1
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py38h06a4308_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.19.2=py38hb070fc8_0
  - ipython=8.10.0=py38h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.1.2=py38h06a4308_0
  - jpeg=9e=h5eee18b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py38h06a4308_0
  - jupyter=1.0.0=py38h06a4308_8
  - jupyter_client=7.4.9=py38h06a4308_0
  - jupyter_console=6.6.2=py38h06a4308_0
  - jupyter_core=5.2.0=py38h06a4308_0
  - jupyter_server=1.23.4=py38h06a4308_0
  - jupyterlab=3.5.3=py38h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.19.0=py38h06a4308_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - krb5=1.19.4=h568e23c_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.9=h16c4e8d_3
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.44.2=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - lightning-utilities=0.9.0=pyhd8ed1ab_0
  - lxml=4.9.1=py38h1edc446_0
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - nbclassic=0.5.2=py38h06a4308_0
  - nbclient=0.5.13=py38h06a4308_0
  - nbconvert=6.5.4=py38h06a4308_0
  - nbformat=5.7.0=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py38h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - notebook=6.5.2=py38h06a4308_0
  - notebook-shim=0.2.2=py38h06a4308_0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numpy-base=1.24.3=py38h31eccc5_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1v=h7f8727e_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py38h6a678d5_0
  - pip=20.3.3=py38h06a4308_0
  - pkgutil-resolve-name=1.3.10=py38h06a4308_0
  - platformdirs=2.5.2=py38h06a4308_0
  - ply=3.11=py38_0
  - prometheus_client=0.14.1=py38h06a4308_0
  - prompt-toolkit=3.0.36=py38h06a4308_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py38h06a4308_0
  - pyqt=5.15.7=py38h6a678d5_1
  - pyqt5-sip=12.11.0=py38h6a678d5_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py38h06a4308_0
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pyzmq=23.2.0=py38h6a678d5_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtconsole=5.4.0=py38h06a4308_0
  - qtpy=2.2.0=py38h06a4308_0
  - qtwebkit=5.212=h4eab89a_4
  - readline=8.2=h5eee18b_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - sip=6.6.2=py38h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py38h06a4308_1
  - soupsieve=2.3.2.post1=py38h06a4308_0
  - sqlite=3.40.1=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py38h06a4308_0
  - tinycss2=1.2.1=py38h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py38h06a4308_0
  - torchvision=0.12.0=py38_cu113
  - tornado=6.2=py38h5eee18b_0
  - traitlets=5.7.1=py38h06a4308_0
  - typing-extensions=4.4.0=py38h06a4308_0
  - typing_extensions=4.4.0=py38h06a4308_0
  - urllib3=1.26.14=py38h06a4308_0
  - webencodings=0.5.1=py38_1
  - websocket-client=0.58.0=py38h06a4308_4
  - wheel=0.38.4=py38h06a4308_0
  - widgetsnbextension=3.5.2=py38h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.4.0
    - addict==2.4.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - albumentations==1.3.0
    - aliyun-python-sdk-core==2.13.36
    - aliyun-python-sdk-kms==2.16.1
    - altair==4.2.2
    - antlr4-python3-runtime==4.9.3
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - attrs==22.2.0
    - awscli==1.27.92
    - backports-zoneinfo==0.2.1
    - black==23.3.0
    - blessed==1.20.0
    - blinker==1.6.2
    - boto3==1.26.92
    - botocore==1.29.92
    - braceexpand==0.1.7
    - cachetools==5.3.0
    - click==8.1.3
    - clip==1.0
    - cloudpickle==2.2.1
    - colorama==0.4.4
    - coloredlogs==15.0.1
    - contourpy==1.0.7
    - crcmod==1.7
    - cycler==0.11.0
    - dataclasses==0.6
    - datadings==3.4.6
    - datasets==2.14.3
    - diffdist==0.1
    - diffusers==0.12.1
    - dill==0.3.7
    - docker-pycreds==0.4.0
    - docutils==0.16
    - easydict==1.10
    - einops==0.3.0
    - exifread-nocycle==3.0.1
    - filelock==3.9.0
    - fire==0.4.0
    - flask==2.3.1
    - flask-cors==3.0.10
    - flatbuffers==23.3.3
    - fonttools==4.39.2
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - ftfy==6.1.1
    - future==0.18.3
    - fvcore==0.1.5.post20221221
    - gast==0.4.0
    - gdown==4.6.4
    - gitdb==4.0.10
    - gitpython==3.1.31
    - google-auth==2.16.2
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - gpustat==1.0.0
    - grpcio==1.51.3
    - h5py==3.9.0
    - huggingface-hub==0.16.4
    - humanfriendly==10.0
    - hydra-core==1.3.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - imagenetv2-pytorch==0.1
    - img2dataset==1.41.0
    - imgaug==0.2.6
    - importlib-metadata==6.0.0
    - importlib-resources==5.12.0
    - invisible-watermark==0.1.5
    - iopath==0.1.9
    - itsdangerous==2.1.2
    - jmespath==0.10.0
    - joblib==1.2.0
    - keras==2.13.1
    - keybert==0.7.0
    - keytotext==2.3.2
    - kiwisolver==1.4.4
    - kornia==0.6.0
    - lazy-loader==0.1
    - libclang==16.0.6
    - markdown==3.4.1
    - markdown-it-py==2.2.0
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - mdurl==0.1.2
    - mmcls==0.25.0
    - mmcv==2.0.1
    - mmcv-full==1.7.1
    - mmengine==0.8.4
    - model-index==0.1.11
    - mpmath==1.3.0
    - msgpack==1.0.5
    - msgpack-numpy==0.4.8
    - multidict==6.0.4
    - multiprocess==0.70.15
    - mypy-extensions==1.0.0
    - natsort==8.3.1
    - networkx==3.0
    - nltk==3.8.1
    - numpy==1.24.2
    - nvidia-ml-py==11.495.46
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - onnx==1.13.1
    - onnxruntime==1.14.1
    - opencv-python==4.1.2.30
    - opencv-python-headless==4.7.0.72
    - opendatalab==0.0.10
    - openmim==0.3.9
    - openxlab==0.0.17
    - opt-einsum==3.3.0
    - ordered-set==4.1.0
    - oss2==2.17.0
    - packaging==23.0
    - pandarallel==1.6.4
    - pandas==1.5.3
    - pathspec==0.11.1
    - pathtools==0.1.2
    - portalocker==2.7.0
    - prettytable==3.6.0
    - promise==2.3
    - protobuf==3.20.3
    - psutil==5.9.4
    - pudb==2019.2
    - pyarrow==12.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.6
    - pycryptodome==3.18.0
    - pydeck==0.8.0
    - pydeprecate==0.3.1
    - pygments==2.14.0
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - pytorch-lightning==2.0.9
    - pytz==2023.3
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - qudida==0.0.4
    - regex==2022.10.31
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rich==13.4.2
    - rsa==4.7.2
    - s3transfer==0.6.0
    - safetensors==0.3.0
    - scikit-image==0.20.0
    - scikit-learn==1.2.2
    - scipy==1.9.1
    - semver==2.13.0
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.97
    - sentry-sdk==1.16.0
    - setproctitle==1.3.2
    - setuptools==60.2.0
    - shapely==1.8.0
    - shortuuid==1.0.11
    - simplebloom==1.0.3
    - simplejpeg==1.6.5
    - smmap==5.0.0
    - streamlit==1.20.0
    - sympy==1.11.1
    - tabulate==0.9.0
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-cpu==2.13.1
    - tensorflow-estimator==2.13.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - termcolor==2.2.0
    - test-tube==0.7.5
    - threadpoolctl==3.1.0
    - tifffile==2023.2.28
    - timm==0.5.4
    - tokenizers==0.12.1
    - toolz==0.12.0
    - torch-fidelity==0.3.0
    - torchmetrics==0.6.0
    - tqdm==4.65.0
    - transformers==4.19.2
    - tzdata==2022.7
    - tzlocal==4.2
    - urwid==2.1.2
    - validators==0.20.0
    - wandb==0.12.21
    - watchdog==2.3.1
    - wcwidth==0.2.6
    - webdataset==0.2.43
    - werkzeug==2.3.0
    - wrapt==1.15.0
    - xxhash==3.3.0
    - yacs==0.1.8
    - yapf==0.32.0
    - yarl==1.8.2
    - yfcc100m==1.0.1
    - zipp==3.15.0
